# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AppLovinSDK'
end

warn_for_unused_master_specs_repo => false